### PR TITLE
fix(aws_signature_v4): Presign Min/Max Expirations

### PR DESCRIPTION
**Pull request by wurikiji**
*Issue #, if available:*

*Description of changes:*

According to the [doc]( https://docs.aws.amazon.com/AmazonS3/latest/API/sigv4-query-string-auth.html), minimum exp value is one second, and maximum exp value is 7 days. 

- change `>` to `>=` and `<` to `<=`
- modify examples to print seven days and one second link

By submitting this pull request, I confirm that you can use, modify, copy, and redistribute this contribution, under the terms of your choice.

### CODE REVIEW

**Comment by dnys1** [comment]
Nice catch! Do you think we should add a test instead of (or in addition to) the example app change? Happy to knock that out if so.

**Comment by wurikiji** [comment]
I think it's enough to have a comment line with a documentation link just like now. 
Actually, I thought the example did not need to be changed. 
If you think the other changes or the addition of a test is required, I will take it.

**Comment by dnys1** [comment]
Sounds good to me! I agree, I think the example change might be a tad confusing. Although I would love to know where a 1-second presigned URL could be used in reality - there must be a good reason they allow it!

**Comment by wurikiji** [comment]
I can't even imagine a good reason for less than 10 seconds link in reality 😃
For one second link, I tried several times to get content from that link by my hand, but I never succeded to use it without the help of code 😅
Do you think I should rollback `example.dart`?

**Comment by dnys1** [comment]
> I can't even imagine a good reason for less than 10 seconds link in reality 😃
> For one second link, I tried several times to get content from that link by my hand, but I never succeded to use it without the help of code 😅

Haha nice!

> Do you think I should �rollback example.dart?

Yeah, let's do that. I'll go ahead and merge afterwards! :)

**Comment by wurikiji** [comment]
Thanks for the quick comments!

**Review by dnys1 — APPROVED** [review]
Thanks for the PR!

**Review by haverchuck — APPROVED** [review]

**Comment by dnys1** [comment]
@wurikiji This has been released in v0.1.1 of the library!

**Pull request merged**
