### PR TITLE
ci: use fastlane to automate version bumping, changelogs, git tags

### PR DESCRIPTION
**Pull request by kaichengyan**
*Issue #, if available:*

*Description of changes:*

* Add fastlane config to automate version bumping, changelogs, git tags.
* Publishing to Pub.dev is still work in progress due to Google OAuth2 issues. 
* This PR doesn't use Fastlane in CircleCI yet. You can test it locally by manually setting the env vars `GITHUB_USER`, `GITHUB_EMAIL`, `CIRCLE_WORKING_DIRECTORY` and merge it to `master` on your own fork.

```
export GITHUB_USER="fastlane-bot"
export GITHUB_EMAIL="fastlane@aws-amplify.com"
export CIRCLE_WORKING_DIRECTORY="~/path/to/amplify-flutter"
```

By submitting this pull request, I confirm that you can use, modify, copy, and redistribute this contribution, under the terms of your choice.

### CODE REVIEW

**Comment by jamesonwilliams** [comment]
Request reviews from @rjuliano @jpignata @iartemiev

**Review by iartemiev — DISMISSED** [review]
LGTM! 🚀

**Comment by haverchuck** [comment]
I don't see where this handles failure logic for publication, i.e. it merges to release branch even in the event that the actual release to pub.dev fails.

**Review by haverchuck — CHANGES_REQUESTED** [review]
1. Needs failure logic for pub.dev publication.

**Review by haverchuck — APPROVED** [review]

**Comment by dnys1** [comment]
Thanks for the PR, @kaichengyan and sorry we were never able to merge this. We've adopted a new tool written in Dart to manage these tasks. All the best!

**Pull request closed without merging**
