### PR TITLE
fix(amplify): upgrade plugin_platform_interface

### PR DESCRIPTION
**Pull request by fjnoyp**
Update  plugin_platform_interface: ^1.0.1 -> ^2.0.0
To fix dependency conflicts with Firebase

*Issue #, if available:* #434
#461 

*Description of changes:*

Upgrade plugin platform interface to 2.0.0 to fix pubspec version conflicts with Firebase and other 3rd party dependencies. 

By submitting this pull request, I confirm that you can use, modify, copy, and redistribute this contribution, under the terms of your choice.

### CODE REVIEW

**Review by jamesonwilliams — APPROVED** [review]

**Comment by haverchuck** [comment]
@fjnoyp Did you do any manual tests?

**Comment by Amplifiyer** [comment]
Also, will this work with customers still using Flutter 1.x?

**Comment by fjnoyp** [comment]
> Also, will this work with customers still using Flutter 1.x?

Yes, it works.  The official documentation says it will work as well: 

https://dart.dev/null-safety/migration-guide#:~:text=Your%20null%2Dsafe%20package%20is,t%20migrated%20to%20null%20safety.

> Your null-safe package is usable by packages and apps that don't use null safety yet, as long as they use Dart 2.12 or later.

**Comment by fjnoyp** [comment]
> @fjnoyp Did you do any manual tests?

Yes, manual tests look good

**Review by haverchuck — APPROVED** [review]

**Review by Ashish-Nanda — APPROVED** [review]

**Pull request merged**
