### PR TITLE
chore: enable dependabot

### PR DESCRIPTION
**Pull request by ragingsquirrel3**
This PR adds needed code changes to enable dependabot for dart projects. See https://github.blog/changelog/2022-04-05-pub-beta-support-for-dependabot-version-updates/ as well as linked thread where there are some questions about monorepos. Per that thread, I believe we need separate entries for all the pubspec locations, so I made a little script to generate that as I expect it to need updates when directory structure changes.

By submitting this pull request, I confirm that you can use, modify, copy, and redistribute this contribution, under the terms of your choice.

### CODE REVIEW

**Review by dnys1 — APPROVED** [review]
Looks good. Script could be cleaned up but not a major issue IMO. Can rewrite in Dart if you want and use `Directory.list(recursive: true)` to make it future proof.

**Review by haverchuck — APPROVED** [review]
This is any annoying nit, but could we put the 'updates' block in alphabetical order? 
Otherwise looks good to me.

**Comment by ragingsquirrel3** [comment]
> This is any annoying nit, but could we put the 'updates' block in alphabetical order? Otherwise looks good to me.

I changed the generation script to sort the output alphabetically.

**Comment by ragingsquirrel3** [comment]
> Looks good. Script could be cleaned up but not a major issue IMO. Can rewrite in Dart if you want and use `Directory.list(recursive: true)` to make it future proof.

Good suggestion, ended up converting to a dart script to do this plus some other things.

**Pull request merged**
