### PR TITLE
Fix crash when remove subscription in case async

### PR DESCRIPTION
**Pull request by thanhminhkma**
*Issue #, if available:*

*Description of changes:*

By submitting this pull request, I confirm that you can use, modify, copy, and redistribute this contribution, under the terms of your choice.

### CODE REVIEW

**Comment by HuiSF** [comment]
Hello @thanhminhkma Thanks for opening the PR, much appreciated.

Could you add a brief summary of what has been changed, and why? Thanks!

**Comment by thanhminhkma** [comment]
@HuiSF 
I got some crash log on firebase with iOS device.

`Crashed: com.apple.main-thread
EXC_BAD_ACCESS KERN_INVALID_ADDRESS 0x0000000000000000
amplify_api
$s11amplify_api17OperationsManagerC15removeOperation11cancelTokenySS_tFZ + 88`

Current source code checking variable on a thread and edit variable on another thread. If cancel multiple times. iOS app will get crash

**Comment by HuiSF** [comment]
Thanks for the explanation @thanhminhkma !
Could you also update relevant unit tests accordingly?

**Comment by dnys1** [comment]
Thank you again for the PR @thanhminhkma. We have merged the iOS fix as part of https://github.com/aws-amplify/amplify-flutter/pull/1598. Was the Android change a fix something you noticed happening or a preemptive fix? I'd love to get that merged as well if it could potentially cause issues.

Sorry for the delay in getting this resolved and thanks for your contribution!

**Pull request closed without merging**
