### PR TITLE
feat(auth): Force refresh

### PR DESCRIPTION
**Pull request by dnys1**
Adds a `forceRefresh` parameter which allows overriding the default refresh logic to perform refreshes on an as-needed basis.

### CODE REVIEW

**Review by Jordan-Nelson — APPROVED** [review]

**Review by ragingsquirrel3 — APPROVED** [review]

**Comment by hoangtronganh** [comment]
@Jordan-Nelson @ragingsquirrel3 
Hi guys,
Can you tell me your release date for this update ?
It is very important to my project.

**Comment by dnys1** [comment]
Hi @hoangtronganh - this was released with amplify_auth_cognito `1.0.0-next.0+5`. If you run `flutter pub upgrade` you should get it automatically. Please give it a whirl and let us know if it works for you!

**Comment by hoangtronganh** [comment]
@dnys1 Thank for support me. 
But i got error when upgrade.

`amplify_auth_cognito: 1.0.0-next.0+5
  amplify_flutter: 1.0.0-next.0+2`

Error:

**Comment by pam-d** [comment]
> @dnys1 Thank for support me. But i got error when upgrade.
> 
> ```
> amplify_auth_cognito: 1.0.0-next.0+5
> amplify_flutter: 1.0.0-next.0+2
> ```
> 
> Error:
> 
> `Because amplify_flutter_ios >=1.0.0-next.0 depends on amplify_core 1.0.0-next.0 and amplify_flutter >=1.0.0-next.0+2 depends on amplify_core >=1.0.0-next.0+1 <1.0.0-next.1, amplify_flutter_ios >=1.0.0-next.0 is incompatible with amplify_flutter >=1.0.0-next.0+2. So, because abc_app depends on amplify_flutter 1.0.0-next.0+2 which depends on amplify_flutter_ios 1.0.0-next.0, version solving failed. pub get failed (1; So, because abc_app depends on amplify_flutter 1.0.0-next.0+2 which depends on amplify_flutter_ios 1.0.0-next.0, version solving failed.)`
> 
> Flutter doctor
> 
> ```
> hoangtronganh@Hoangs-MacBook-Pro abc_app % flutter doctor
> Doctor summary (to see all details, run flutter doctor -v):
> [✓] Flutter (Channel stable, 3.0.5, on macOS 11.6 20G165 darwin-arm, locale en)
> [✓] Android toolchain - develop for Android devices (Android SDK version 32.1.0-rc1)
> [✓] Xcode - develop for iOS and macOS (Xcode 13.2.1)
> [✓] Chrome - develop for the web
> [✓] Android Studio (version 2021.1)
> [✓] VS Code (version 1.71.0)
> [✓] Connected device (3 available)
>     ! Error: anhht is busy: Making anhht ready for development. Xcode will continue when
>       anhht is finished. (code -10)
> [✓] HTTP Host Availability
> 
> • No issues found!
> ```

Used the following combination:
```
amplify_core: 1.0.0-next.0+1
amplify_flutter: 1.0.0-next.0+3
amplify_auth_cognito: 1.0.0-next.0+5
amplify_authenticator: 1.0.0-next.0+3
```

On the other hand, wondering when will this feature be merged/released on published versions.

**Pull request merged**
