### PR TITLE
feat(auth): TOTP MFA

### PR DESCRIPTION
**Pull request by dnys1**
Introduces TOTP MFA with registration and verification flows. There are no new APIs for this approach. Instead, confirmSignIn is leveraged with two new sign in step types: `mfaSetup` and `confirmSignInWithTotpMfaCode`.

---

**Stack**:
- #1769
- #1768
- #1767

⚠️ *Part of a stack created by [spr](https://github.com/ejoffe/spr). Do not merge manually using the UI - doing so may have unexpected results.*

### CODE REVIEW

**Comment by schreyerpeter** [comment]
@dnys1 Thanks for tackling this! When do you estimate this feature will be released?

**Comment by dnys1** [comment]
@schreyerpeter no firm at the moment unfortunately. We are looking to how best to release this and will add an update to the TOTP tracking ticket (https://github.com/aws-amplify/amplify-flutter/issues/574) when we have a good estimate.

**Comment by schreyerpeter** [comment]
> @schreyerpeter no firm timelines at the moment unfortunately. We are looking to how best to release this and will add an update to the TOTP tracking ticket (#574) when we have a good estimate.

Thank you very much! I'll keep an eye on that thread.

**Review by thanhhung0096 — APPROVED** [review]

**Comment by chrisdadej** [comment]
@dnys1 / @abdallahshaban557 Just checking to see if there's an update on getting this change merged and released?
Anything that we can help with to get it over the line? I'd like to avoid forking the code and maintaining a seperate instance just to get something as fundamental as 2FA in place for Flutter.

Note: There is one other API that's missing `getPreferredMFA()` in order to determine the user's current setting. Happy to help put that together if it can all be merged in together.

**Comment by abdallahshaban557** [comment]
Hi @chrisdadej - we are getting really close to shipping this feature. We are just finalizing some interface changes to align our implementation to the other Amplify libraries. How soon do you need this?

**Comment by chrisdadej** [comment]
@abdallahshaban557 In development... yesterday :) In production we are targeting July 1 hence thinking of what a Plan B looks like if this functionality isn't ready.

If you need extra testers, or help in building out for example the `getPreferredMFA()` API please let me know. More than happy to help - it doesn't have to have perfect feature parity with the React library, but the auth / cognito / 2fa capabilities are a must.

**Comment by abdallahshaban557** [comment]
Understood - thank you for pushing us to get this out sooner. We are trying our best to get it out ASAP, and we will keep your offer in mind to help us get this out sooner if possible. Thank you so much! Helping us test sounds amazing actually!

**Comment by dnys1** [comment]
Closing in favor of https://github.com/aws-amplify/amplify-flutter/pull/3146

**Pull request closed without merging**
